### ISSUE TITLE
formatting FYI

### ISSUE THREAD

**Issue by cod33** [ajd98/molecularvolume#2]
Hi, Alex,

There seems to be a compatibility error with a format statement in the command line. In line 92 of pdb2volume.py, `print(u"Volume: {:.01f} \u00c5^3".format(v))` throws an error: 

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xc5' in position 16: ordinal not in range(128)

Obviously, taking the formatting step out of the print statement gives the volume answer. Adding `.encode('utf8')` to the end of the statement bypasses the error (as suggested [here](https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20)), but prints "_^3" rather than the Angstrom symbol. 

Loving the tool! Thanks for sharing it :)

**Comment by ajd98** [comment]
Thanks for reporting this.  This error likely occurs because Python chooses an encoding for stdout based on your locale, and your locale does not support characters outside of the standard ASCII range of 0-127.  I'm pushing a fix that removes unicode to improve compatibility for systems with odd locales, but  you might consider updating your locale (e.g., to en_US.utf-8) if you want unicode characters to print properly to your terminal.
